id: P752E8778
initial_creation_type: input
source_metadata:
  title: Khenpo Kunzang Palden Series
  language: en
  description: 'Texts by and about Khenpo Kunzang Palden (kun bzang dpal ldan, 1862–1943),
    alias Khenpo Kunpal, an important disciple of Patrul Rinpoche and author of a
    celebrated commentary on the Bodhicaryāvatāra:'
  volume:
    9322a2adef9b42fd9af398c556d34143:
      title: 'Lightning Bands of Compassion: A Song of Lament for Khenchen Kunzang
        Palden Tupten Chökyi Drakpa'
      parent: Songs
created_at: '2022-03-01T00:25:56.627616'
last_modified_at: '2022-03-01T00:25:56.627622'
